server:
  port: 8088
spring:
  application:
    #应用的名称，可选
    name: oa_demo
  servlet:
    multipart:
      max-file-size: 10MB       # 单个文件最大 50MB
      max-request-size: 100MB   # 总上传请求大小最大 100MB
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/oa_demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: deleted  # 逻辑删除字段名
      logic-not-delete-value: 0  # 未删除值
      logic-delete-value: 1     # 已删除值

oa:
  path: D:\oa_demo_files\